#!/bin/sh
set -e

echo "INITIALIZING WITH $DB_PASSWORD";
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $DB_USERNAME with encrypted password '$DB_PASSWORD';
    CREATE USER $TEST_DB_USERNAME with encrypted password '$TEST_DB_PASSWORD';
    CREATE DATABASE $DB_NAME;
    CREATE DATABASE $TEST_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USERNAME;
    GRANT ALL PRIVILEGES ON DATABASE $TEST_DB_NAME TO $TEST_DB_USERNAME;
EOSQL
