FROM adoptopenjdk/openjdk11:alpine-slim
RUN addgroup -S tzb && adduser -S tzb-user -G tzb
USER tzb-user
ARG DEPENDENCY=target
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["sh", "-c", "java -cp  app:app/lib/* ${JAVA_OPTS} com.kshitijpatil.tazabazar.ApiServerApplication ${0} ${@}"]