version: "3.8"

services:
    database:
        image: postgres:13-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secret
        env_file:
            - .env
        volumes:
            - ./postgres/0-init-roles.sh:/docker-entrypoint-initdb.d/0-init-roles.sh
    backend:
        build: ./backend
        env_file:
            - .env
        depends_on: 
            - "database"
        ports:
            - "8080:8080"
